version: "3.8"
services:
  mysql:
    image: mariadb:10.8.3
    container_name: books_mysql
    platform: linux/arm64/v8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: books_catalogue
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

networks:
  tutorial:

volumes:
  db-data:
